title: "Ben Jiles"
tagline: "Pizza-induced thoughts of a cybersec professional and cypherpunk enthusiast"
description: "Ben Jiles cybersec blog"
github_username: ben-jiles
baseurl: 
url: "https://ben-jiles.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
